### ISSUE TITLE
IllegalAccessError when trying to configure protobuf from another plugin

### ISSUE THREAD

**Issue by martintreurnicht** [google/protobuf-gradle-plugin#289]
We have a gRPC plugin that in our `buildSrc` that does a couple of things, one of them is configuring the protobuf plugin, recently when trying to convert to Kotlin DSL using 0.8.7, we get the following error:

```bash
java.lang.IllegalAccessError: tried to access method org.gradle.kotlin.dsl.NamedDomainObjectContainerScope.<init>(Lorg/gradle/api/NamedDomainObjectContainer;)V from class com.google.protobuf.gradle.ProtobufConfiguratorExtsKt$plugins$1
	at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt$plugins$1.invoke(ProtobufConfiguratorExts.kt:90)
	at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt$plugins$1.invoke(ProtobufConfiguratorExts.kt)
	at org.gradle.kotlin.dsl.KotlinClosure1.doCall(GroovyInteroperability.kt:97)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:427)
	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:148)
	at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:142)
	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:106)
	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:39)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:103)
	at org.gradle.util.ConfigureUtil$configure.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at com.google.protobuf.gradle.ProtobufConfigurator.plugins(ProtobufConfigurator.groovy:86)
	at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt.plugins(ProtobufConfiguratorExts.kt:26)
```

Only seems to affect the plugins

**Comment by marcoferrer** [comment]
What version of Gradle are you using and does the error still occur using the lastest protobuf plugin snapshot?

**Comment by martintreurnicht** [comment]
We're using Gradle 5.1, let me try it with the latest snapshot and i'll let you know

**Comment by martintreurnicht** [comment]
Using snapshot build i now get a new issues:

```bash
Caused by: org.gradle.api.UnknownDomainObjectException: ExecutableLocator with name '1.16.1' not found.
```

when evaluating:
```kotlin
project.protobuf {
            protoc {
                artifact = "com.google.protobuf:protoc:1.16.1"
            }

            plugins {
                grpc {
                    artifact = "io.grpc:protoc-gen-grpc-java:1.16.1"
                }
            }

            generateProtoTasks {
                all().forEach {
                    plugins {
                        grpc {}
                    }
                }
            }
        }
```

Specificially when running the `plugins` lamda

More potentially helpful output:

```bash
at com.google.protobuf.gradle.KtDslCompatibilityUtils.configureNamedDomainObjectContainer(KtDslCompatibilityUtils.java:32)
	at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt$plugins$1.invoke(ProtobufConfiguratorExts.kt:88)
	at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt$plugins$1.invoke(ProtobufConfiguratorExts.kt)
	at org.gradle.kotlin.dsl.KotlinClosure1.doCall(GroovyInteroperability.kt:97)
	at jdk.internal.reflect.GeneratedMethodAccessor1505.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:427)
	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:148)
	at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:142)
	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:106)
	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:39)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:103)
	at org.gradle.util.ConfigureUtil$configure.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
	at com.google.protobuf.gradle.ProtobufConfigurator.plugins(ProtobufConfigurator.groovy:86)
	at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt.plugins(ProtobufConfiguratorExts.kt:87)
```

**Comment by drmaas** [comment]
@marcoferrer I can confirm I am getting the same error in gradle 5.1, but it works fine for gradle 4.10.2. Sanitized example:

```
import com.google.protobuf.gradle.protobuf
import com.google.protobuf.gradle.protoc
import com.google.protobuf.gradle.plugins
import com.google.protobuf.gradle.generateProtoTasks
import com.google.protobuf.gradle.id
import com.google.protobuf.gradle.ofSourceSet

val grpcVersion by extra { "1.17.1" }

plugins {
    java
    id("nebula.kotlin").version("1.3.11")
    id("com.google.protobuf").version("0.8.7")
}

repositories {
    jcenter()
}

dependencies {
    implementation("com.google.inject:guice:4.2.1")
    implementation("com.google.protobuf:protobuf-java-util:3.6.1")
    implementation("io.grpc:grpc-protobuf:$grpcVersion")
    implementation("io.grpc:grpc-stub:$grpcVersion")
    if (JavaVersion.current().isJava9Compatible) {
        // Workaround for @javax.annotation.Generated
        // see: https://github.com/grpc/grpc-java/issues/3633
        implementation("javax.annotation:javax.annotation-api:1.3.1")
    }

    testImplementation("org.jetbrains.kotlin:kotlin-test")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")
    testImplementation("ch.qos.logback:logback-classic:1.2.3")
}

sourceSets.named("main").configure {
    java {
        setSrcDirs(listOf("$buildDir/generated/source/proto/main/java", "$buildDir/generated/source/proto/main/grpc"))
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.6.1"
    }
    plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:1.17.1"
        }
    }
    generateProtoTasks {
        ofSourceSet("main").forEach {
            it.plugins {
                id("grpc")
            }
        }
    }
}
```

**Comment by marcoferrer** [comment]
So I think the latest snapshot might not be up to date with head of master or I was having some weird caching issues. I tried running the example project from master under gradle 5.1 and didnt receive any errors. @zhangkun83 Are snapshots automatically built on merge to master?

**Comment by zhangkun83** [comment]
No, snapshots have to be pushed manually. I just pushed the latest one.

**Comment by martintreurnicht** [comment]
Seems to be fixed in master, when building my own snapshot version it now works, would be great to get a 0.8.8 release out there

**Comment by zhangkun83** [comment]
FYI 0.8.8 is now released.
