### ISSUE TITLE
Protobuf Gradle plugin cannot generate C# code 

### ISSUE THREAD

**Issue by xaviarias** [google/protobuf-gradle-plugin#297]
When generating Protobuf with the plugin, I need to use a `protobuf` dependency with a 3rd party library because their proto files are not compiled in C#. E.g.:
```groovy
dependencies {
    protobuf "org.hyperledger.fabric-chaincode-java:fabric-chaincode-protos:$fabricVersion"
}
```
However, I get an error when running the `generateProto` task because some [Google proto files](https://github.com/protocolbuffers/protobuf/blob/7fdc45a854a9e177559ad99e991c06ed1777e480/src/google/protobuf/compiler/plugin.proto#L47) are in v2 syntax.

Here is the trace:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':conduent-healthcare-service-grpc:generateProto'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.accept(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.accept(ExecuteActionsTaskExecuter.java:117)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:184)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ResolveIncrementalChangesTaskExecuter.execute(ResolveIncrementalChangesTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:46)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: protoc: stdout: . stderr: peer/transaction.proto: warning: Import google/protobuf/timestamp.proto but not used.
--csharp_out: google/protobuf/compiler/plugin.proto: C# code generation only supports proto3 syntax
```

**Comment by zhangkun83** [comment]
This is an issue with the protobuf compiler. Please file the issue with the [protobuf project](https://github.com/protocolbuffers/protobuf).

**Comment by xaviarias** [comment]
Hi @zhangkun83 , sorry to come back through this issue but I did open a [ticket](https://github.com/protocolbuffers/protobuf/issues/5711#issuecomment-463476831) in Prootbuf project and has been closed before being fixed. Please could you have a look?

**Comment by ejona86** [comment]
@xaviarias, C# protobuf does not support proto 2. It's as simple as that. It's quite understandable that support doesn't want to be added. But there's definitely nothing to be done about it here.

**Comment by xaviarias** [comment]
Hi @ejona86 , the issue happens when generating C# in proto 3. 

The [google/protobuf/compiler/plugin.proto](https://github.com/protocolbuffers/protobuf/blob/3.7.x/src/google/protobuf/compiler/plugin.proto) file is in proto 2 which makes the plugin fail.

**Comment by ejona86** [comment]
The normal csharp code generator is implemented in C++, so it is able to read the plugin.proto in order to learn what to generate.

**Comment by ejona86** [comment]
@zhangkun83, since this is a `protobuf` dependency, and @xaviarias is using a java-generated as its base, I think protobuf-java is also being extracted and attempting to be built. It seems there would be no way of avoiding that automatically (as any dependencies have to be built, but it is hard to know which files are actual dependencies).

@xaviarias, try:
```gradle
dependencies {
    protobuf ("org.hyperledger.fabric-chaincode-java:fabric-chaincode-protos:$fabricVersion") {
        exclude group: 'com.google.protobuf', module: 'protobuf-java'
    }
}
```

**Comment by xaviarias** [comment]
Thanks @ejona86 , it worked! That was impressive 👏

**Comment by TheRealJagwire** [comment]
Apologies on resurrecting this issue, but is the exclude line above for Xavi a general solution to this problem? I need to generate both Java and C# files....
