### ISSUE TITLE
Protobuf fails with NPE if protoc is null

### ISSUE THREAD

**Issue by will-sargent-eero** [google/protobuf-gradle-plugin#337]
If the protoc path is not found by the ExecutableLocator, then the path is appended as null and we get "Cannot invoke method length() on null object":

```groovy
      int baseCmdLength = baseCmd.sum { it.length() + CMD_ARGUMENT_EXTRA_LENGTH }
```

where the source is

```
    List<String> baseCmd = [ tools.protoc.path ]
    baseCmd.addAll(dirs)
```

with the result:

```
Caused by: java.lang.NullPointerException: Cannot invoke method length() on null object
        at com.google.protobuf.gradle.GenerateProtoTask$_generateCmds_closure2.doCall(GenerateProtoTask.groovy:142)
        at com.google.protobuf.gradle.GenerateProtoTask.generateCmds(GenerateProtoTask.groovy:142)
        at com.google.protobuf.gradle.GenerateProtoTask$generateCmds$5.callStatic(Unknown Source)
        at com.google.protobuf.gradle.GenerateProtoTask.compile(GenerateProtoTask.groovy:501)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
```

It'd be good to have a null check here to ensure the path is never null.

**Comment by voidzcy** [comment]
`protoc` has to be there before executing the commend, we assume this is the precondition and definitely it should fail when the provided `protoc` path/artifact is invalid.

**Comment by will-sargent-eero** [comment]
This is showing up in a plugin that I am putting together to reduce some of the boilerplate involved in [ScalaPB with Gradle](https://scalapb.github.io/faq.html#how-do-i-use-scalapb-with-gradle):

```groovy
class ScalaPbPlugin implements Plugin<Project>  {

    String scalaMajorVersion = "2.11"
    String scalapbVersion = "0.9.0-M7" 
    
    @Override
    public void apply(Project project) {
        project.getPluginManager().apply(JavaTestFixturesPlugin.class);
        project.getPluginManager().apply(ProtobufPlugin.class);
        project.getPluginManager().apply(JavaPlugin.class);

        project.ext.set("scalapbVersion", scalapbVersion)

        project.plugins.withType(ScalaPlugin) {
            project.compileJava.enabled = false
            project.dependencies {
                // MUST be implementation even though it says "runtime" on the library
                implementation "com.thesamet.scalapb:scalapb-runtime_${scalaMajorVersion}:${scalapbVersion}"
                implementation "com.thesamet.scalapb:scalapb-runtime-grpc_${scalaMajorVersion}:${scalapbVersion}"

                testFixturesImplementation "com.thesamet.scalapb:scalapb-runtime_${scalaMajorVersion}:${scalapbVersion}"
                testFixturesImplementation "com.thesamet.scalapb:scalapb-runtime-grpc_${scalaMajorVersion}:${scalapbVersion}"
            }
        }

        project.plugins.withType(ProtobufPlugin) {
            project.protobuf {
                protoc {
                    artifact = 'com.google.protobuf:protoc:3.7.1'
                }
                plugins {
                    scalapb {
                        artifact = (org.gradle.nativeplatform.platform.internal.DefaultNativePlatform.getCurrentOperatingSystem().isWindows()) ?
                                "com.thesamet.scalapb:protoc-gen-scalapb:${scalapbVersion}:windows@bat" :
                                "com.thesamet.scalapb:protoc-gen-scalapb:${scalapbVersion}:unix@sh"
                    }
                }
                generateProtoTasks {
                    all().each { task ->
                        task.builtins {
                            remove java
                        }
                        task.plugins {
                            scalapb {
                                // add any ScalaPB generator options here. See: https://scalapb.github.io/scalapbc.html#passing-generator-parameters
                                option 'flat_package'
                                option 'grpc'
                            }
                        }
                    }
                }
            }

            project.sourceSets { sourceSet ->
                sourceSet.main.proto.srcDirs "src/main/protobuf"
                project.plugins.withType(ScalaPlugin) {
                    sourceSet.main.scala {
                        srcDirs "${project.protobuf.generatedFilesBaseDir}/main/scalapb"
                    }
                }
                sourceSet.test.proto.srcDirs "src/test/protobuf"
            }
        }
    }
}

```
