### ISSUE TITLE
Random issues when using reflection on a proto generated class using other messages

### ISSUE THREAD

**Issue by keith-miller** [google/protobuf-gradle-plugin#342]
Java version: `openjdk version "11.0.4" 2019-07-16` (also tested on `openjdk version "1.8.0_222"`)
Gradle version: `5.6.2` (also tested on `4.10.3`)
Protobuf version: `3.9.0`
Protobuf Gradle plugin version: `0.8.10`

So, I am working on a library that is dependent on reflection, Protobufs and the Protobuf Gradle plugin, and I have encountered a strange issue. My unit tests are failing some of the time, passing others, with the same code. 

I have a test proto with the following defined:

```
message BasicMessage {
    string entity_id = 1;
    string name = 2;
    int32 count = 3;
    BasicChildMessage child = 4;
}

message BasicChildMessage {
    string entity_id = 1;
    string name = 2;
}
```

The test involves calling reflection on `BasicMessage.newBuilder().setChild(BasicChildMessage message)`. Sometimes reflection parses the method parameter as `BasicChildMessage`, and sometimes it parses it as `BasicChildMessage$Builder`, which is the return type. 

Failure:
```
Testing started at 7:43 PM ...
> Task :extractIncludeProto
> Task :extractProto
> Task :generateProto
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :extractIncludeTestProto
> Task :extractTestProto
> Task :generateTestProto
> Task :compileTestJava
> Task :processTestResources
> Task :testClasses
> Task :test FAILED
Setter parameter type: com.keithtmiller.prototest.BasicChildMessage$Builder
Result type: class com.keithtmiller.prototest.BasicChildMessage

Error converting field: child
com.keithtmiller.protoconverter.ProtoConverterException: Error converting field: child
  ...
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.keithtmiller.protoconverter.ProtoConverter.convertProtoClass(ProtoConverter.java:230)
	at com.keithtmiller.protoconverter.ProtoConverter.processFields(ProtoConverter.java:91)
	... 91 more
```

Success:
```
Testing started at 7:44 PM ...
> Task :extractIncludeProto
> Task :extractProto
> Task :generateProto
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :extractIncludeTestProto
> Task :extractTestProto
> Task :generateTestProto
> Task :compileTestJava
> Task :processTestResources
> Task :testClasses
> Task :test
Setter parameter type: com.keithtmiller.prototest.BasicChildMessage
Result type: class com.keithtmiller.prototest.BasicChildMessage
...
10 actionable tasks: 10 executed
7:44:34 PM: Task execution finished 'test'.
```

Open to suggestions. 

Example code can be found at: https://github.com/keith-miller/proto-converter/tree/odd_reflection_issue

Thanks!

**Comment by keith-miller** [comment]
Closing, this was an issue on my end. Did not realize that the generated message class will have setters for the other message class **and** the other message class _builder._
