### ISSUE TITLE
Missing output directives when compiling on android with gradle kotlin dsl

### ISSUE THREAD

**Issue by jishindev** [google/protobuf-gradle-plugin#349]
Below is the config for proto in kotlin DSL for gradle i managed to write up from multiple sources as a definitive example wasn't out there that i could find. This is the first time for me working with proto. 

```
import com.google.protobuf.gradle.*
import org.gradle.kotlin.dsl.protobuf
import org.jetbrains.kotlin.gradle.internal.AndroidExtensionsExtension
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("com.android.application")
    kotlin("android")
    kotlin("android.extensions")
    id("com.google.protobuf")
    kotlin("kapt")
}

android {
    compileSdkVersion(29)
    defaultConfig {        
      ...
    }
    buildTypes {
       ...
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    sourceSets.onEach {
        it.java.srcDir("src/${it.name}/kotlin")
    }

    // Add generated code folder to app module source set
    sourceSets.getByName("main")
        .java.srcDirs("${protobuf.protobuf.generatedFilesBaseDir}/main/javalite")

    protobuf { files("src/main/proto/") }
}

val grpcVersion = "1.24.0"
protobuf.protobuf.run {

    protoc {
        artifact = "com.google.protobuf:protoc:3.10.0"
    }

    plugins {
        id("javalite") { artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0" }
        id("grpc") { artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion" }
    }

    generateProtoTasks {
        ofSourceSet("main").forEach {
            it.plugins {
                id("grpc") { option("lite") }
                id("javalite") {}
            }
            it.builtins { id("java") {} }
            it.generateDescriptorSet = true
        }
    }
}

...

dependencies {

// Kotlin
    implementation(kotlin("stdlib-jdk7", version = "1.3.21"))
  
   ...

// Protobuf & gRPC
    implementation("io.grpc:grpc-okhttp:$grpcVersion")
    implementation("io.grpc:grpc-protobuf-lite:$grpcVersion")
    implementation("io.grpc:grpc-stub:$grpcVersion")
    
    ...
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-XXLanguage:+InlineClasses")
        jvmTarget = "1.8"
    }
}
```

The compile time error I get when I try to sync this is - 
```
Execution failed for task ':app:generateDebugProto'.
> protoc: stdout: . stderr: Missing output directives.
```

Here's the full stacktrace - 

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:generateDebugProto'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:151)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:148)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:141)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionStateTaskExecuter.execute(ResolveBeforeExecutionStateTaskExecuter.java:75)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:49)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:49)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.GradleException: protoc: stdout: . stderr: Missing output directives.

        at com.google.protobuf.gradle.GenerateProtoTask.compileFiles(GenerateProtoTask.groovy:533)
        at com.google.protobuf.gradle.GenerateProtoTask.compile(GenerateProtoTask.groovy:503)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:702)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:669)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:404)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:393)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:376)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:213)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:201)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:77)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:120)
        ... 35 more
```

**Comment by zhangkun83** [comment]
Can you try
```
./gradlew --info clean build 2>&1 | grep '^\[.*protoc'
```
and paste the output here?

**Comment by jishindev** [comment]
Right after posting this issue, I happen to find some other example which used Kotlin DSL for proto config and everything works now. This is what it looks like after the changes - 

```import com.google.protobuf.gradle.*
import org.gradle.kotlin.dsl.protobuf
import org.jetbrains.kotlin.gradle.internal.AndroidExtensionsExtension
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("com.android.application")
    kotlin("android")
    kotlin("android.extensions")
    id("com.google.protobuf")
    kotlin("kapt")
}

android {
    compileSdkVersion(29)
    defaultConfig {        
      ...
    }
    buildTypes {
       ...
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    sourceSets.onEach {
        it.java.srcDir("src/${it.name}/kotlin")
    }

    // Add generated code folder to app module source set
    sourceSets.getByName("main")
        .java.srcDirs("${protobuf.protobuf.generatedFilesBaseDir}/main/javalite")
}

val grpcVersion = "1.24.0"
protobuf.protobuf.run {

    generatedFilesBaseDir = "$projectDir/src"

    protoc {
        artifact = "com.google.protobuf:protoc:3.10.0"
    }

    plugins {
        id("javalite") { artifact = "com.google.protobuf:protoc-gen-javalite:3.0.0" }
        id("grpc") { artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion" }
    }

    generateProtoTasks {
        all().forEach {
            it.builtins {
              //  remove("java")
            }

            it.plugins{
                create("javalite"){
                    outputSubDir="java"
                }
                create("grpc") {
                    option("lite")
                }
            }
        }
    }
}

...

dependencies {

// Kotlin
    implementation(kotlin("stdlib-jdk7", version = "1.3.21"))
  
   ...

// Protobuf & gRPC
    implementation("io.grpc:grpc-okhttp:$grpcVersion")
    implementation("io.grpc:grpc-protobuf-lite:$grpcVersion")
    implementation("io.grpc:grpc-stub:$grpcVersion")
    
    ...
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-XXLanguage:+InlineClasses")
        jvmTarget = "1.8"
    }
}```

May be you can include a proper configuration doc with each possible config type for proto with Kotlin DSL on Android. Thanks.

**Comment by ab5y** [comment]
I am having the same error. Can't really tell whether the above solution would be valid for me. I downloaded the protoc compiler for win64, before which Android Studio was complaining about not finding the protoc compiler. Once I put it on the path, I got the `Missing output directives` error.
My gradle file is the following:

`plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id "com.google.protobuf"
}

android {
    compileSdk 31

    defaultConfig {
        applicationId "com.ab5y.gradualepub"
        minSdk 24
        targetSdk 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation("androidx.datastore:datastore:1.0.0")
    // optional - RxJava2 support
    implementation("androidx.datastore:datastore-rxjava2:1.0.0")
    // optional - RxJava3 support
    implementation("androidx.datastore:datastore-rxjava3:1.0.0")
    implementation 'com.google.protobuf:protobuf-java:3.19.1'
    implementation 'com.google.protobuf:protobuf-kotlin:3.19.1'
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.4.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.2'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}`

**Comment by ab5y** [comment]
> I am having the same error on Win10. Can't really tell whether the above solution would be valid for me since it's been 2 years. I downloaded the protoc compiler for win64, before which Android Studio was complaining about not finding the protoc compiler. Once I put it on the path, I got the `Missing output directives` error. My gradle file is the following:
> 
> ```
> plugins {
>     id 'com.android.application'
>     id 'kotlin-android'
>     id "com.google.protobuf"
> }
> 
> android {
>     compileSdk 31
> 
>     defaultConfig {
>         applicationId "com.ab5y.gradualepub"
>         minSdk 24
>         targetSdk 30
>         versionCode 1
>         versionName "1.0"
> 
>         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
>     }
> 
>     buildTypes {
>         release {
>             minifyEnabled false
>             proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
>         }
>     }
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
>     kotlinOptions {
>         jvmTarget = '1.8'
>     }
> }
> 
> dependencies {
>     implementation("androidx.datastore:datastore:1.0.0")
>     // optional - RxJava2 support
>     implementation("androidx.datastore:datastore-rxjava2:1.0.0")
>     // optional - RxJava3 support
>     implementation("androidx.datastore:datastore-rxjava3:1.0.0")
>     implementation 'com.google.protobuf:protobuf-java:3.19.1'
>     implementation 'com.google.protobuf:protobuf-kotlin:3.19.1'
>     implementation 'androidx.core:core-ktx:1.3.2'
>     implementation 'androidx.appcompat:appcompat:1.4.0'
>     implementation 'com.google.android.material:material:1.4.0'
>     implementation 'androidx.constraintlayout:constraintlayout:2.1.2'
>     testImplementation 'junit:junit:4.+'
>     androidTestImplementation 'androidx.test.ext:junit:1.1.2'
>     androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
> }
> ```

Might have fixed this issue by removing the `id "com.google.protobuf"` at the top

**Comment by Nailik** [comment]
I had the same issue in a kotlin multiplatform project, inside the sub android project.
After changing my gradle file to this it works:
```
plugins {
    id("com.google.protobuf") version "0.8.17"
}

dependencies {
    implementation("androidx.datastore:datastore:1.0.0")
    implementation("com.google.protobuf:protobuf-kotlin:3.19.4")
}

protobuf {

    protoc {
        artifact = "com.google.protobuf:protoc:3.19.4"
    }

    generateProtoTasks {
        all().forEach { task ->
            task.plugins{
                create("kotlin")
                create("java")
            }
        }
    }
}
```

**Comment by waletoye** [comment]
> 3.19.4

works thanks 🙏🏼

@Nailik  can i call you saviour?

**Comment by aamernabi** [comment]
> I had the same issue in a kotlin multiplatform project, inside the sub android project. After changing my build.gradle.kts to this it works:
> 
> ```
> plugins {
>     id("com.google.protobuf") version "0.8.17"
> }
> 
> dependencies {
>     implementation("androidx.datastore:datastore:1.0.0")
>     implementation("com.google.protobuf:protobuf-kotlin:3.19.4")
> }
> 
> protobuf {
> 
>     protoc {
>         artifact = "com.google.protobuf:protoc:3.19.4"
>     }
> 
>     generateProtoTasks {
>         all().forEach { task ->
>             task.plugins{
>                 create("kotlin")
>                 create("java")
>             }
>         }
>     }
> }
> ```

Thanks it works with gradle-kotlin..

**Comment by crowforkotlin** [comment]
> I had the same issue in a kotlin multiplatform project, inside the sub android project.我在 kotlin 多平台项目中遇到了同样的问题，在 sub android 项目内。 After changing my build.gradle.kts to this it works:将我的 build.gradle.kts 更改为此后，它可以工作：
> 
> ```
> plugins {
>     id("com.google.protobuf") version "0.8.17"
> }
> 
> dependencies {
>     implementation("androidx.datastore:datastore:1.0.0")
>     implementation("com.google.protobuf:protobuf-kotlin:3.19.4")
> }
> 
> protobuf {
> 
>     protoc {
>         artifact = "com.google.protobuf:protoc:3.19.4"
>     }
> 
>     generateProtoTasks {
>         all().forEach { task ->
>             task.plugins{
>                 create("kotlin")
>                 create("java")
>             }
>         }
>     }
> }
> ```

Thanks for the help this is really very useful!
