### ISSUE TITLE
Stop using deprecated NamedDomainObjectContainer.invoke(kotlin.Function1)

### ISSUE THREAD

**Issue by simolus3** [google/protobuf-gradle-plugin#495]
Using the protobuf plugin with a recent gradle version prints

```
Using method NamedDomainObjectContainer<T>.invoke(kotlin.Function1) has been deprecated. This is scheduled to be removed in Gradle 8.0. Recompile your plugin against Gradle >= 6.8 Consult the upgrading guide for further information: https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#using_NamedDomainObjectContainer_invoke_kotlin_Function1
        at org.gradle.kotlin.dsl.NamedDomainObjectContainerExtensionsKt.invoke(NamedDomainObjectContainerExtensions.kt:61)
        at com.google.protobuf.gradle.KtDslCompatibilityUtils.configureNamedDomainObjectContainer(KtDslCompatibilityUtils.java:32)
        at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt$plugins$1.invoke(ProtobufConfiguratorExts.kt:123)
        at com.google.protobuf.gradle.ProtobufConfiguratorExtsKt$plugins$1.invoke(ProtobufConfiguratorExts.kt)
        at org.gradle.kotlin.dsl.KotlinClosure1.doCall(GroovyInteroperability.kt:94)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        // ...
```

The problem is [this wrapper](https://github.com/google/protobuf-gradle-plugin/blob/46825f926494db226c0a6b1f325c31d16a26324a/src/main/groovy/com/google/protobuf/gradle/KtDslCompatibilityUtils.java#L32), which still uses the old function with a kotlin function interface instead of the Gradle `Action` class. I tried to fix this myself but it looks like `org.gradle:gradle-kotlin-dsl` is no longer getting published and the version this project depends on doesn't have the new api yet. I think that wrapper should create an action and use the newer method if its running in Gradle >=6.8 to avoid the deprecation warning.

**Comment by simolus3** [comment]
Sorry for the duplicate, I somehow missed that when searching. I'm using Gradle 7 so it works for me, I was just complaining about the deprecation warning.
