### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method shouldDiscardUnknownFields()Z in class Lcom/google/protobuf/CodedInputStream

### ISSUE THREAD

**Issue by mf-acst** [google/protobuf-gradle-plugin#521]
After updating my android project to use gradle 7.0.0, and updating the protobuf gradle plugin from 0.8.10 to 0.8.17, I now get a crash when trying to convert json to a protobuf object. 

I am curretly using version 3.17.3 for the protobuf-java and protobuf-java-util libraries. I am not using the lite versions.

I also created an issue explaining this in the protobuf library repo. That tread can be seen here: https://github.com/protocolbuffers/protobuf/issues/8956

```
java.lang.NoSuchMethodError: No virtual method shouldDiscardUnknownFields()Z in class Lcom/google/protobuf/CodedInputStream; or its super classes (declaration of 'com.google.protobuf.CodedInputStream' appears in /data/app/com.acst.android.integratedtests-aBjTJTaWJ5dUqf2RXITKng==/base.apk)
    at com.google.protobuf.GeneratedMessageV3$ExtendableMessage.parseUnknownField(GeneratedMessageV3.java:1133)
    at com.google.protobuf.DescriptorProtos$ServiceOptions.<init>(DescriptorProtos.java:34316)
    at com.google.protobuf.DescriptorProtos$ServiceOptions.<init>(DescriptorProtos.java:34256)
    at com.google.protobuf.DescriptorProtos$ServiceOptions$1.parsePartialFrom(DescriptorProtos.java:35280)
    at com.google.protobuf.DescriptorProtos$ServiceOptions$1.parsePartialFrom(DescriptorProtos.java:35274)
    at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:497)
    at com.google.protobuf.DescriptorProtos$ServiceDescriptorProto.<init>(DescriptorProtos.java:19025)
    at com.google.protobuf.DescriptorProtos$ServiceDescriptorProto.<init>(DescriptorProtos.java:18960)
    at com.google.protobuf.DescriptorProtos$ServiceDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:20089)
    at com.google.protobuf.DescriptorProtos$ServiceDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:20083)
    at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:497)
    at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1299)
    at com.google.protobuf.DescriptorProtos$FileDescriptorProto.<init>(DescriptorProtos.java:1201)
    at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:4888)
    at com.google.protobuf.DescriptorProtos$FileDescriptorProto$1.parsePartialFrom(DescriptorProtos.java:4882)
    at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:139)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:173)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:190)
    at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
    at com.google.protobuf.DescriptorProtos$FileDescriptorProto.parseFrom(DescriptorProtos.java:2297)
    at com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(Descriptors.java:410)
    at com.acst.overwatch.OverwatchClass.<clinit>(OverwatchClass.java:1582)
    at com.acst.overwatch.AvailableVirtualCheckIns$Builder.getDescriptorForType(AvailableVirtualCheckIns.java:560)
    at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1451)
    at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:1338)
    at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:476)
    at com.acst.android.sharedtestresources.utils.ProtobufUtil.json2Proto(ProtobufUtil.kt:13)```

**Comment by ejona86** [comment]
Since that is a runtime failure, it isn't a problem with this plugin. The plugin only runs protoc to generate code; it has no direct interaction with proguard or the like.
