### ISSUE TITLE
version 0.8.15 causes extractIncludeProto to fail in Gradle 7

### ISSUE THREAD

**Issue by Toldry** [google/protobuf-gradle-plugin#550]
After upgrading our project to Gradle 7 and upgrading the plugin to  0.8.15 , running `./gradlew extractIncludeProto` causes the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':socialmedia-server-api:extractIncludeProto'.
> Querying the mapped value of provider(interface java.util.Set) before task ':socialmedia-server-api:processResources' has completed is not supported
```

# Notes
- This error does not occur in 0.8.14 ✅, but it does in versions 0.8.15 ❌ and above
- According to the [gradle docs](https://docs.gradle.org/6.8/userguide/upgrading_version_6.html#querying_a_mapped_output_property_of_a_task_before_the_task_has_completed): 

> Querying the value of a mapped output property before the task has completed can cause strange build failures because it indicates stale or non-existent outputs may be used by mistake. This behavior is deprecated and will emit a deprecation warning. This will become an error in Gradle 7.0.

**Comment by Toldry** [comment]
Here's the output when running the task with `--full-stacktrace` :

```
Execution failed for task ':socialmedia-server-api:extractIncludeProto'.
> Querying the mapped value of provider(interface java.util.Set) before task ':socialmedia-server-api:processResources' has completed is not supported

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':socialmedia-server-api:extractIncludeProto'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.gradle.api.InvalidUserCodeException: Querying the mapped value of provider(interface java.util.Set) before task ':socialmedia-server-api:processResources' has completed is not supported
	at org.gradle.api.internal.provider.TransformBackedProvider.lambda$beforeRead$0(TransformBackedProvider.java:84)
	at org.gradle.api.internal.provider.BuildableBackedProvider$1.visitProducerTasks(BuildableBackedProvider.java:56)
	at org.gradle.api.internal.provider.ValueSupplier$ValueProducer.visitContentProducerTasks(ValueSupplier.java:59)
	at org.gradle.api.internal.provider.TransformBackedProvider.beforeRead(TransformBackedProvider.java:81)
	at org.gradle.api.internal.provider.TransformBackedProvider.calculateOwnValue(TransformBackedProvider.java:63)
	at org.gradle.api.internal.provider.AbstractMinimalProvider.get(AbstractMinimalProvider.java:84)
	at org.gradle.api.internal.provider.ProviderResolutionStrategy$2.resolve(ProviderResolutionStrategy.java:33)
	at org.gradle.api.internal.file.collections.ProviderBackedFileCollection.visitChildren(ProviderBackedFileCollection.java:63)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:119)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:351)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:119)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:74)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.visitContents(DefaultConfigurableFileCollection.java:372)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitChildren(DefaultConfigurableFileCollection.java:284)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:119)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:351)
	at org.gradle.api.internal.file.FileCollectionBackedFileTree.visitContents(FileCollectionBackedFileTree.java:98)
	at org.gradle.api.internal.file.FileCollectionBackedFileTree.visitContentsAsFileTrees(FileCollectionBackedFileTree.java:73)
	at org.gradle.api.internal.file.FilteredFileTree.visitChildren(FilteredFileTree.java:66)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:119)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:351)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:119)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:64)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:89)
	at org.gradle.api.internal.file.DefaultFileCollectionFactory$ResolvingFileCollection.visitChildren(DefaultFileCollectionFactory.java:333)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:119)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:351)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:119)
	at org.gradle.api.internal.tasks.PropertyFileCollection.visitChildren(PropertyFileCollection.java:48)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:119)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:351)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.lambda$detectMissingDependencies$5(LocalTaskNodeExecutor.java:99)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at com.google.common.collect.RegularImmutableSortedSet.forEach(RegularImmutableSortedSet.java:86)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.detectMissingDependencies(LocalTaskNodeExecutor.java:97)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.lambda$execute$0(LocalTaskNodeExecutor.java:71)
	at org.gradle.api.internal.tasks.execution.TaskExecution.validate(TaskExecution.java:477)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:78)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:57)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:76)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:50)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNoEmptySources(SkipEmptyWorkStep.java:249)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:54)
	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:43)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:31)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:287)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:144)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Toldry** [comment]
Any updates?

**Comment by Thrillpool** [comment]
Same issue here. For me it happens if I exclude any task which populates the build directory.

**Comment by ejona86** [comment]
8df229f was released today in v0.8.19

**Comment by Thrillpool** [comment]
@ejona86 That's true, appreciated, but it still has the issue this topic concerns, that if you exclude tasks that Gradle knows populates the build directory while running extractIncludeProto, then the task fails. I can't really upgrade until it is resolved, as some of the developers at my work do that sort of thing (i.e. exclude certain tasks) regularly.

**Comment by Thrillpool** [comment]
Fair point re no reproduction.

Here is a minimal reproduction

https://github.com/Thrillpool/gradle-protobuf-bug/commit/720c56ca5c821611e738c82396f57c9797b20384

Run `./gradlew :p2:build -x compileScala` and you will see "Querying the mapped value of provider(interface java.util.Set) before task ':p1:compileScala' has completed is not supported".

I will make a fix over the weekend.

**Comment by ejona86** [comment]
That's a pretty compact reproduction. Looks like it is happening before the task runs. I suspected something strange like that might be happening, but it isn't obvious how to resolve the issue if the other task will never be run.
```
2022-06-30T15:15:42.882-0700 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Task :p2:extractIncludeProto' started
2022-06-30T15:15:42.882-0700 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Snapshot inputs and outputs before executing task ':p2:extractIncludeProto'' started
2022-06-30T15:15:42.883-0700 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Snapshot inputs and outputs before executing task ':p2:extractIncludeProto''
2022-06-30T15:15:42.882-0700 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] 
2022-06-30T15:15:42.882-0700 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :p2:extractIncludeProto FAILED
2022-06-30T15:15:42.882-0700 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter] Putting task artifact state for task ':p2:extractIncludeProto' into context took 0.0 secs.
2022-06-30T15:15:42.882-0700 [DEBUG] [org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep] Implementation for task ':p2:extractIncludeProto': com.google.protobuf.gradle.ProtobufExtract_Decorated@ffaa5fe2ef2dd247bdaa8dce5cc335ff
2022-06-30T15:15:42.882-0700 [DEBUG] [org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep] Additional implementations for task ':p2:extractIncludeProto': [com.google.protobuf.gradle.ProtobufExtract_Decorated@ffaa5fe2ef2dd247bdaa8dce5cc335ff]
2022-06-30T15:15:42.883-0700 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Snapshot inputs and outputs before executing task ':p2:extractIncludeProto'' completed
```

**Comment by Thrillpool** [comment]
I have a fix, the troublesome line is this one

https://github.com/google/protobuf-gradle-plugin/commit/bf6301ac28c22c78eb930c7f249ebbb7f691b5aa#diff-ce7f3a5cefd661ce9628d8d55b9ed9a02ff244a8a10dbcfd012818bad47a6e5eR150

inputFiles.getElements().map ... is the 'mapped provider' that Gradle is complaining about.

Is there anything I should know regarding the tests for this project? When I clone the repo as is and run the tests I get 30 pass, 50 fail. The errors themselves are along the lines of 

'Caused by: org.gradle.api.GradleException: protoc: stdout: . stderr: test1.proto: File not found.'

I am on Windows, if it is significant. I'm sure I can work it out myself so if it's not something known don't worry.

**Comment by rougsig** [comment]
I will check this issue on sunday.

**Comment by ejona86** [comment]
@Thrillpool, I've not seen failures like that. I honestly don't know if the tests have recently been run on Windows, so that may indeed be the problem.

**Comment by rougsig** [comment]
@Thrillpool
Some ways to workaround the problem:
1. You cannot exclude `compile`, `processResources` tasks. All other tasks can be excluded for this task without problems.
2. Don't create dependencies between modules with the protobuf plugin. i.e. in your test project you have p2 dependent on p1. They both have the protobuf plugin, so don't do that.

---

@Toldry 
Could you provide a gradle scan for the `extractIncludeProto` task? Just add the `--scan` argument and accept the Gradle publishing terms, then post the scan link in a comment.

If you are unable to provide a scan:
Does the project have modules with the protobuf plugin and does it depend on another module with the protobuf plugin?
Could you please describe structure of your project. I'm interested in cross-module dependencies and plugins.
Project structure example:
```
├── p1
    ├── plugins: android, scala, protobuf
├── p2
    ├── dependencies: api p1
    ├── plugins: kotlin, java, protobuf
├── p3
    ├── dependencies: api p1, implementaion p2
    ├── plugins: kotlin, java, protobuf
```

---

**What is actually going on inside:**
To add [protos-in-dependencies](https://github.com/google/protobuf-gradle-plugin#protos-in-dependencies) feature, `extractIncludeProto` task uses source set compile classpath. This means that the task `extractIncludeProto` depends on the `compile` task of the dependent module. (yes, the plugin runs a compile task to generate prototypes, it's weird but it's true)
<details>
  <summary>Gradle scan screenshot</summary>


https://scans.gradle.com/s/wnbz2soej3hnw/timeline


![image](https://user-images.githubusercontent.com/18681794/177048639-9c673edd-00c7-4315-8f7a-fe53303e3b9e.png)

</details>

`:p2:extractIncludeProto` input files from [test project](https://github.com/Thrillpool/gradle-protobuf-bug)
```
gradle-protobuf-bug/p1/build/resources/main
gradle-protobuf-bug/p1/build/classes/java/main
gradle-protobuf-bug/p1/build/classes/scala/main
```

So I guess it's a slightly different issue. `extractIncludeProto` task should not depend on compiled classes, it should depends only on `*.proto` files.

**Comment by Thrillpool** [comment]
Neither of those workarounds sound especially practical for me.

1. People want to do that, I'm not going to upset their workflow and tell them they can't.
2. That's how our project is setup, there's no real chance of me reshuffling around such that it isn't this way.

To me it seems like either https://github.com/google/protobuf-gradle-plugin/pull/452 should be reverted, given that it's just an optimisation anyway.

Or https://github.com/google/protobuf-gradle-plugin/commit/bf6301ac28c22c78eb930c7f249ebbb7f691b5aa#diff-ce7f3a5cefd661ce9628d8d55b9ed9a02ff244a8a10dbcfd012818bad47a6e5eR150 line should be resolved. To me it seemed like it could be fixed just by restructuring the logic a bit. 

It wants to do this map of the provider and do a objectFactory.fileCollection().from on the mapped thing. But could we not just eagerly get inputFiles.getElements(), and just do some logic on the resulting Set<FileSystemLocation> and objectFactory.fileCollection().from the Set<Object> we make.

**Comment by rougsig** [comment]
I'll try to find the best solution for the issue this week.

**Comment by vlsi** [comment]
It looks like protobuf plugin attempts to scan compile classpath and find .proto files there.

Is there a real need to scan classpath? What if users who want .proto from jars would add the deps to a special protobuf configuration? Then compileClasspath scanning won't be needed, and exclusion of compileScala won't break proto tasks

**Comment by rougsig** [comment]
There is no real need.  It is necessary to change the logic of work from dependencies.  Stop taking dependencies from implementation, take them only from protobuf.

**Comment by rougsig** [comment]
Details about "don't depend on compilation tasks" here https://github.com/google/protobuf-gradle-plugin/issues/578.

**Comment by scottsue** [comment]
Hi,

Apologies for resurrecting an old thread here but I am getting this exact issue whilst running the latest 0.9.4 plugin.  I've tried to downgrade down to 0.8.14 and as the OP experienced the error doesn't show up.

I'm not excluding any tasks as others have experienced here, I am running a simple `./gradlew build`

A workaround that seems to work at the moment is

`tasks.named("extractIncludeProto").configure {
    mustRunAfter(tasks.named("processResources"))
}`

It seems strange to have to need this, also is this suggestive that extractIncludeProto and processResources are running together in parallel?

Is there something that I'm missing in my build.gradle, or a genuine issue still to be resolved?
