### ISSUE TITLE
Add documentation to clarify gradle deps for android.

### ISSUE THREAD

**Issue by carl-mastrangelo** [google/protobuf-gradle-plugin#94]
When trying to use with Android studio, an exception is raised:

```
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.google.protobuf']
    at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:160)
    at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:112)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:35)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:79)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:135)
    at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
    at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
    at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:35)
    at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
    ... 60 more
Caused by: org.gradle.internal.reflect.ObjectInstantiationException: Could not create an instance of type com.google.protobuf.gradle.ProtobufSourceDirectorySet_Decorated.
    at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:51)
    at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
    at org.gradle.api.internal.plugins.DefaultConvention.create(DefaultConvention.java:106)
    at com.google.protobuf.gradle.ProtobufPlugin$_addSourceSetExtensions_closure7.doCall(ProtobufPlugin.groovy:150)
    at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
    at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
    at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:115)
    at org.gradle.api.DomainObjectCollection$all.call(Unknown Source)
    at com.google.protobuf.gradle.ProtobufPlugin.addSourceSetExtensions(ProtobufPlugin.groovy:149)
    at com.google.protobuf.gradle.ProtobufPlugin.doApply(ProtobufPlugin.groovy:108)
    at com.google.protobuf.gradle.ProtobufPlugin$_apply_closure1.doCall(ProtobufPlugin.groovy:86)
    at com.sun.proxy.$Proxy46.execute(Unknown Source)
    at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:205)
    at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:203)
    at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:110)
    at org.gradle.api.internal.plugins.DefaultPluginManager.withPlugin(DefaultPluginManager.java:208)
    at org.gradle.api.plugins.PluginManager$withPlugin.call(Unknown Source)
    at com.google.protobuf.gradle.ProtobufPlugin$_apply_closure2.doCall(ProtobufPlugin.groovy:91)
    at com.google.protobuf.gradle.ProtobufPlugin.apply(ProtobufPlugin.groovy:90)
    at com.google.protobuf.gradle.ProtobufPlugin.apply(ProtobufPlugin.groovy)
    at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
    at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:44)
    at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
    ... 71 more
Caused by: java.lang.NoClassDefFoundError: org/gradle/api/internal/file/collections/DefaultDirectoryFileTreeFactory
    at com.google.protobuf.gradle.ProtobufSourceDirectorySet.<init>(ProtobufSourceDirectorySet.groovy:47)
    at com.google.protobuf.gradle.ProtobufSourceDirectorySet_Decorated.<init>(Unknown Source)
    at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:49)
    ... 93 more
```

This is confusing, as the documentation for protobug gradle plugin says it needs Gradle 2.12, which is clearly in the default build.gradle:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.7.7'
...
```

The problem is that "2.1.2" is visually similar to "2.12".  The solution is mentioned [here](https://developer.android.com/studio/releases/gradle-plugin.html#updating-gradle).  `gradle/wrapper/gradle-wrapper.properties` needs to be updated to 2.12 (or 2.14.1 as of this writing).

Additionally, Android studio forces 2.10 by default, and ignores the wrapper script which is also confusing.

**Comment by zhangkun83** [comment]
Are you suggesting in addition to document that "Gradle 2.12" is required, we also add reference to instructions on how to check and upgrade Gradle version?
